name: Continuous Integration

env:
  DB_URI: ${{secrets.DB_URI}}
  BETA_JUDGE_URI: ${{secrets.BETA_JUDGE_URI}}
  PROD_JUDGE_URI: ${{secrets.PROD_JUDGE_URI}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - main
      - release
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Lint check
        run: npm run lint
      - name: Unit tests
        run: npm run test
        env:
          CI: true
          ISOLATE: true
      - name: build
        run: npm run build
