name: Deploy

env:
  APP_NAME: edugator-service-api
  S3_BUCKET: edugator-service-api-bucket
  AWS_REGION: us-east-1
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
  DB_URI: ${{secrets.DB_URI}}
  BETA_JUDGE_URI: ${{secrets.BETA_JUDGE_URI}}
  PROD_JUDGE_URI: ${{secrets.PROD_JUDGE_URI}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

on:
  push:
    branches:
      - release

jobs:
  create_eb_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create .env file
        run: |
          cat << EOF >> .env
          BETA_JUDGE_URI=${{secrets.BETA_JUDGE_URI}}
          PROD_JUDGE_URI=${{secrets.PROD_JUDGE_URI}}
          NODE_ENV=production
          DB_URI=${{secrets.DB_URI}}
          JWT_SECRET=${{secrets.JWT_SECRET}}
          EOF

      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Creating Source bundle"
          zip -r ${{env.APP_NAME}}.zip src/ Dockerfile docker-compose.yml .env .dockerignore package.json .eslintrc .eslintignore .prettierrc tsconfig.json tsconfig.release.json jest.config.js
          S3_KEY="$AWS_VERSION_LABEL.zip"

          echo "Uploading Source bundle to s3"
          aws s3 cp ${{env.APP_NAME}}.zip s3://${{env.S3_BUCKET}}/${S3_KEY} --region ${{env.AWS_REGION}}

          echo "Creating Elastic Beanstalk version"
          aws elasticbeanstalk create-application-version --application-name ${{env.APP_NAME}} --version-label $AWS_VERSION_LABEL --region ${{env.AWS_REGION}} --source-bundle S3Bucket=${{env.S3_BUCKET}},S3Key=${S3_KEY} --auto-create-application

  deploy_aws:
    needs: [create_eb_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-id: ${{ secrets.AWS_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Installing Elastic Beanstalk Cli"
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

          echo "Deploy init"
          eb init -i ${{env.APP_NAME}} -p ${{env.AWS_PLATFORM}} -k ${{secrets.AWS_ID}} --region ${{env.AWS_REGION}}
          eb deploy ${{env.APP_NAME}} --version ${AWS_VERSION_LABEL}
          echo "Deploy finished"
